import test from 'node:test'; import assert from 'node:assert/strict';
import { createWriter } from '../src/writer.js';
const a=Object.freeze({SCALES:[{id:0,name:'Major (Ionian)',pcs:[0,2,4,5,7,9,11]},{id:1,name:'Dorian',pcs:[0,2,3,5,7,9,10]}],parseChordName:x=>x.trim()==='Cm7'?{root:0,intervals:[0,3,7,10],displayName:'Cm7'}:x.trim()==='F7'?{root:5,intervals:[0,4,7,10],displayName:'F7'}:null,getDiatonicTetrads:()=>[],getHarmonicFunction:()=>null});
const base={title:'test',bpm:125,key:{root_pc:0},scaleIdx:1,form:['A'],sections:[{name:'A',bars:1,time_signature:{beats:4,note_value:4},events:[{bar:1,beat:1,chord:' Cm7 ',extras:{future:['kept']},midi_snapshot:[60,63,67]},{bar:1,beat:3,chord:'F7',offset_ticks:-240}]}]};
test('factory writes pure v0.2 and preserves extras/snapshot',()=>{const got=createWriter(a)(base,'1.0.0','2026-07-23T00:00:00Z');assert.equal(got.format_version,'0.2');assert.equal(got.sections[0].chords[0].chord,'Cm7');assert.deepEqual(got.sections[0].chords[0].future,['kept']);assert.deepEqual(got.sections[0].chords[0].midi_snapshot,[60,63,67]);assert.equal(got.sections[0].chords[0].function,'')});
for(const [n,f] of [['empty title',x=>x.title=''],['bad version',x=>x],['linked half',x=>x.linked_als={project:'/x'}],['same onset',x=>x.sections[0].events.push({bar:1,beat:1,chord:'F7'})],['offset',x=>x.sections[0].events[0].offset_ticks=1920],['duration',x=>x.sections[0].events[0].duration_ticks=1920]])test('reject '+n,()=>{const x=structuredClone(base);f(x);assert.throws(()=>createWriter(a)(x,n==='bad version'?'':'1','2026-07-23T00:00:00Z'))});
test('adapter boundary rejects malformed dependency',()=>assert.throws(()=>createWriter({})));
test('writer preserves B ownership while accepting its anticipation after A',()=>{const x=structuredClone(base);x.form=['A','B'];x.sections.push({name:'B',bars:1,time_signature:{beats:4,note_value:4},events:[{bar:1,beat:1,chord:'F7',offset_ticks:-120}]});const got=createWriter(a)(x,'1','2026-07-23T00:00:00Z');assert.deepEqual(got.sections[1].chords[0],{bar:1,beat:1,chord:'F7',offset_ticks:-120,function:''});});
test('writer rejects a repeated section when its first occurrence anticipates before the loop',()=>{const x=structuredClone(base);x.form=['B','A','B'];x.sections.push({name:'B',bars:1,time_signature:{beats:4,note_value:4},events:[{bar:1,beat:1,chord:'F7',offset_ticks:-120}]});assert.throws(()=>createWriter(a)(x,'1','2026-07-23T00:00:00Z'),/Onset outside loop/);});
