import { flattenTimeline } from './timeline.js';
const bases=new Set([0,5,7,14]);
const bad=m=>{throw new Error(m)};
function validAdapter(a){return a&&['parseChordName','getDiatonicTetrads','getHarmonicFunction'].every(k=>typeof a[k]==='function')&&Array.isArray(a.SCALES)&&a.SCALES.every(s=>s&&typeof s.name==='string'&&s.name&&Array.isArray(s.pcs)&&s.pcs.length&&s.pcs.every(n=>Number.isInteger(n)&&n>=0&&n<=11))&&!Object.values(a).some(v=>v&&typeof v.then==='function')}
export function createWriter(adapter){
  if(!validAdapter(adapter)||Object.values(adapter).some(v=>v&&typeof v.then==='function')) bad('Invalid theoryAdapter');
  const scales = structuredClone(adapter.SCALES);
  return function write(draft,runtimeVersion,generatedAt){
    if(!draft||typeof draft.title!=='string'||!draft.title.trim()) bad('title is required');
    if(typeof runtimeVersion!=='string'||!runtimeVersion.trim()) bad('runtimeVersion is required');
    if(typeof generatedAt!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/.test(generatedAt)||Number.isNaN(Date.parse(generatedAt))) bad('generatedAt must be UTC RFC3339'); const z=new Date(generatedAt), m=generatedAt.match(/^(\d+)-(\d+)-(\d+)T(\d+):(\d+):(\d+)/); if(!m||z.getUTCFullYear()!=m[1]||z.getUTCMonth()+1!=m[2]||z.getUTCDate()!=m[3]||z.getUTCHours()!=m[4]||z.getUTCMinutes()!=m[5]||z.getUTCSeconds()!=m[6]) bad('generatedAt must be real UTC');
    if(!Number.isFinite(draft.bpm)||draft.bpm<=0||!Number.isInteger(draft.key?.root_pc)||draft.key.root_pc<0||draft.key.root_pc>11) bad('Invalid top-level');
    const scale=scales[draft.scaleIdx]; if(!scale||!Array.isArray(draft.form)||!draft.form.length) bad('Invalid scale or form');
    if(draft.linked_als&&(!draft.linked_als.project||typeof draft.linked_als.project!=='string'||!/^\//.test(draft.linked_als.project)||typeof draft.linked_als.als_scene!=='string'||!draft.linked_als.als_scene.trim())) bad('Incomplete linked_als');
    const sections=(draft.sections??[]).map(s=>{if(!Number.isInteger(s.bars)||s.bars<1)bad('Invalid bars');const beats=s.time_signature?.beats,note=s.time_signature?.note_value,beatTicks=480*4/note,barTicks=beatTicks*beats;if(!Number.isInteger(beats)||!Number.isInteger(note)||!Number.isInteger(beatTicks))bad('Invalid time signature');const chords=(s.events??s.chords??[]).map(x=>{const p=adapter.parseChordName(x.chord);if(!p)bad('Invalid chord');const e={...structuredClone(x.extras??{}),bar:x.bar,beat:x.beat,chord:p.displayName};for(const k of ['offset_ticks','duration_ticks','midi_snapshot'])if(x[k]!==undefined)e[k]=structuredClone(x[k]);if(!Number.isInteger(e.bar)||!Number.isInteger(e.beat)||e.bar<1||e.bar>s.bars||e.beat<1||e.beat>beats||!Number.isInteger(e.offset_ticks??0)||Math.abs(e.offset_ticks??0)>=barTicks)bad('Invalid event');if(e.offset_ticks===0)delete e.offset_ticks;if(e.duration_ticks!==undefined&&(!Number.isInteger(e.duration_ticks)||e.duration_ticks<=0||e.duration_ticks>barTicks*(s.bars-e.bar+1)))bad('Invalid duration');if(e.midi_snapshot!==undefined&&(!Array.isArray(e.midi_snapshot)||!e.midi_snapshot.length||e.midi_snapshot.some((n,i)=>!Number.isInteger(n)||n<0||n>127||(i&&n<=e.midi_snapshot[i-1]))))bad('Invalid midi_snapshot');const pcs=[...new Set(p.intervals.map(n=>(p.root+n)%12))].sort((a,b)=>a-b).join(',');const ts=adapter.getDiatonicTetrads(scale.pcs,draft.key.root_pc,4);const i=ts.findIndex(t=>t.rootPC===p.root&&[...t.pcs].map(n=>(t.rootPC+n)%12).sort((a,b)=>a-b).join(',')===pcs);if(i>=0){if(typeof ts[i].degree!=='string')bad('Malformed tetrad');e.degree=ts[i].degree;const fn=bases.has(scale.id)?adapter.getHarmonicFunction(scale.id,i):null;if(fn!==null&&typeof fn!=='string')bad('Malformed function');e.function=fn===null?'':fn}else e.function='';return e}).sort((a,b)=>((a.bar-1)*barTicks+(a.beat-1)*beatTicks+(a.offset_ticks??0))-((b.bar-1)*barTicks+(b.beat-1)*beatTicks+(b.offset_ticks??0)));return{name:s.name,bars:s.bars,time_signature:structuredClone(s.time_signature),chords}});
    const out={format:'pad-sensei-progression',format_version:'0.2',ppq:480,title:draft.title,bpm:draft.bpm,key:{root_pc:draft.key.root_pc,scale:scale.name},sections,form:structuredClone(draft.form),generated_by:`64PE ${runtimeVersion}`,generated_at:generatedAt};if(draft.linked_als)out.linked_als={project:draft.linked_als.project,als_scene:draft.linked_als.als_scene.trim()};flattenTimeline(out);return out;
  }
}
